x-development-volumes: &development-volumes
  volumes:
    - ./docs:/workspace/app/docs/
    - ./tests:/workspace/app/tests/
    - ./tools:/workspace/app/tools/
    - ./app:/workspace/app/app/
    - ./Makefile:/workspace/app/Makefile
    - ./pyproject.toml:/workspace/app/pyproject.toml
    - ./uv.lock:/workspace/app/uv.lock
    - ./tsconfig.json:/workspace/app/tsconfig.json
    - ./package.json:/workspace/app/package.json
    - ./package-lock.json:/workspace/app/package-lock.json
    - ./vite.config.ts:/workspace/app/vite.config.ts
    - ./resources:/workspace/app/resources
    - ./public:/workspace/app/public
    - ./components.json:/workspace/app/components.json
    - ./tailwind.config.cjs:/workspace/app/tailwind.config.cjs
    - ./postcss.config.cjs:/workspace/app/postcss.config.cjs
    - ./.env.docker.example:/workspace/app/.env

services:
  app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.dev
    ports:
      - "8000:8000"
      - "3006:3006"
    image: app:latest-dev
    tty: true
    environment:
      VITE_USE_SERVER_LIFESPAN: "true" # true in dev or run
      SAQ_USE_SERVER_LIFESPAN: "false"
    command: litestar run --reload --host 0.0.0.0 --port 8000
    restart: always
    <<: *development-volumes
  worker:
    image: app:latest-dev
    command: litestar workers run
    tty: true
    restart: always
    <<: *development-volumes
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

    env_file:
      - .env.docker.example
  migrator:
    image: app:latest-dev
    command: litestar database upgrade --no-prompt
    restart: "no"
    <<: *development-volumes
    env_file:
      - .env.docker.example
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
