"""Add session store

Revision ID: 1f2d9a6c1b3e
Revises: 386593b41af9
Create Date: 2025-12-28 00:00:00.000000+00:00

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import GUID, DateTimeUTC

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC

# revision identifiers, used by Alembic.
revision = "1f2d9a6c1b3e"
down_revision = "386593b41af9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_store",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("namespace", sa.String(length=255), nullable=False),
        sa.Column("value", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTimeUTC(timezone=True), nullable=True),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_store")),
        sa.UniqueConstraint("key", "namespace", name="uq_session_store_key_namespace"),
    )
    with op.batch_alter_table("session_store", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_store_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index("ix_session_store_key_namespace_unique", ["key", "namespace"], unique=True)
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_store", schema=None) as batch_op:
        batch_op.drop_index("ix_session_store_key_namespace_unique")
        batch_op.drop_index(batch_op.f("ix_session_store_expires_at"))

    op.drop_table("session_store")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
